name: graphql_codegen_example

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1
  graphql_flutter: 5.0.2-beta.2
  flutter:
    sdk: flutter


dev_dependencies:
  json_serializable: ^6.1.3
  graphql_codegen: 
    path: "../"
  build_runner: ^2.0.3
  test: ^1.17.4
